import { createApp } from 'vue'
import App from './App.vue'
import './assets/styles/styleInterno.css'
import './assets/styles/articleNews.css'
import './assets/styles/Blogstyle.css'
import './assets/styles/ourProject.css'
import './assets/styles/slider.css'
import './assets/styles/bannerstyle.css'
// import './assets/styles/styleslider.css'
import store from './store/index.js'
import router from './router'
// import './assets/js/sort.js'
createApp(App).use(router).use(store).mount('#app')
