import { createApp } from 'vue'
import App from './App.vue'
import './assets/styles/styleInterno.css'
import './assets/styles/articleNews.css'
import './assets/styles/Blogstyle.css'
import './assets/styles/ourProject.css'
import './assets/styles/slider.css'
import store from './store/index.js'
// import './assets/js/sort.js'
createApp(App).use(store).mount('#app')
